"""
Structured next steps.

Turns guidance and research findings into something a user can act on, grouped
the way a person actually needs it: what to do now, what can wait, what to try
if the first option is closed, what is worth keeping, what she might choose to
tell someone, and what nobody knows.

Relationship to ``action_planner``
----------------------------------
``backend/agents/action_planner.py`` produces an ``ActionPlan`` of
``ActionItem``s from verified evidence, using the LLM. It is **not replaced**.
This module is a deterministic presentation layer on top of it: it buckets
existing actions, and it can build a minimal plan with no LLM at all.

That second property is the point. When Gemini is unavailable — which it has
been throughout this project's validation — a woman in danger must still get
concrete steps. ``emergency_fallback()`` is pure Python and always available.

Design rules enforced here
--------------------------
- **Proportionate.** A simple question gets one or two steps, not a programme.
  ``build_workflow`` caps "do now" at three items for non-critical situations.
- **Never mandatory reporting.** Going to the police is offered, never required;
  there is no code path that inserts it as a non-optional step.
- **Never confrontation.** A filter removes any action that suggests confronting
  the person causing harm, whatever its source.
- **Provenance preserved.** Research-backed steps keep their URLs, and every
  step is labelled with where it came from.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Sequence

from backend.models.research import SafetyWorkflow, Urgency

logger = logging.getLogger(__name__)


class StepSource(str, Enum):
    """Where a step came from — kept visible so the user can weigh it."""

    #: Derived from a verified source with a URL.
    RESEARCH = "research"
    #: Fixed guidance that does not depend on any provider.
    DETERMINISTIC = "deterministic"
    #: Generated by the model. Advice, not established fact.
    GENERATED = "generated"


@dataclass
class WorkflowStep:
    text: str
    source: StepSource = StepSource.GENERATED
    source_urls: List[str] = field(default_factory=list)
    #: True when nothing breaks if the user skips this.
    optional: bool = True

    def to_dict(self) -> Dict[str, Any]:
        return {
            "text": self.text,
            "source": self.source.value,
            "source_urls": self.source_urls,
            "optional": self.optional,
            "is_verified_fact": self.source is StepSource.RESEARCH,
        }


@dataclass
class ActionWorkflow:
    """Next steps, grouped by when and whether they matter."""

    do_now: List[WorkflowStep] = field(default_factory=list)
    next_steps: List[WorkflowStep] = field(default_factory=list)
    alternatives: List[WorkflowStep] = field(default_factory=list)
    #: Steps worth keeping in a Safety Center plan.
    save: List[WorkflowStep] = field(default_factory=list)
    #: Information the user *may choose* to send someone. Never sent for her.
    share: List[WorkflowStep] = field(default_factory=list)
    limitations: List[str] = field(default_factory=list)
    needs_clarification: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "do_now": [s.to_dict() for s in self.do_now],
            "next": [s.to_dict() for s in self.next_steps],
            "alternatives": [s.to_dict() for s in self.alternatives],
            "save": [s.to_dict() for s in self.save],
            "share": [s.to_dict() for s in self.share],
            "limitations": self.limitations,
            "needs_clarification": self.needs_clarification,
            "not_professional_advice": (
                "This is information to help you decide, not legal, medical or "
                "psychological advice, and HerWay is not representing you."
            ),
        }

    @property
    def is_empty(self) -> bool:
        return not (self.do_now or self.next_steps or self.alternatives)


# ---------------------------------------------------------------------------
# Confrontation filter
# ---------------------------------------------------------------------------
# Applied to every step regardless of origin. Telling someone to confront a
# person who may hurt them is the single most dangerous thing this product
# could output, and a model can produce it in any phrasing.

_CONFRONTATION_PATTERNS = [
    r"\bconfront\b",
    r"\btell (him|her|them) (you know|to stop|that you)\b",
    r"\bask (him|her|them) (to stop|why|directly)\b",
    r"\bface (him|her|them)\b",
    r"\bstand up to (him|her|them)\b",
    r"\bwarn (him|her|them) that\b",
    r"\bthreaten to (report|expose|tell)\b",
    # `apolog\b` would not match "apology" — the boundary falls after "apolog",
    # before the "y". Match the word stem and let it run to the end.
    r"\bdemand (an )?(apolog\w*|explanation)",
]
_CONFRONTATION_RE = re.compile("|".join(_CONFRONTATION_PATTERNS), re.IGNORECASE)


def suggests_confrontation(text: str) -> bool:
    return bool(text) and bool(_CONFRONTATION_RE.search(text))


def strip_confrontation(steps: Sequence[WorkflowStep]) -> List[WorkflowStep]:
    """Drop any step advising confrontation, whatever produced it."""
    kept = []
    for step in steps:
        if suggests_confrontation(step.text):
            logger.warning(
                "ActionWorkflow: removed a step suggesting confrontation "
                "(source=%s)",
                step.source.value,
            )
            continue
        kept.append(step)
    return kept


# ---------------------------------------------------------------------------
# Deterministic emergency guidance
# ---------------------------------------------------------------------------

def emergency_fallback() -> ActionWorkflow:
    """Concrete steps for immediate danger, with no provider involved.

    Every number here is a national Indian helpline carried in
    ``backend/india_resources.py`` with an official source. Nothing in this
    function calls a model, a search engine or a database, so it works when
    everything else is down.

    Note what is absent: no instruction to confront anyone, no promise that
    help will arrive in a given time, and no claim that HerWay has told
    anybody anything.
    """
    workflow = ActionWorkflow()
    workflow.do_now = [
        WorkflowStep(
            "If you can, move to where other people are — a shop, a neighbour's "
            "door, a busy street.",
            StepSource.DETERMINISTIC,
            optional=False,
        ),
        WorkflowStep(
            "Call 112. It reaches police, ambulance and fire from any phone in India.",
            StepSource.DETERMINISTIC,
            optional=False,
        ),
        WorkflowStep(
            "181 is the women helpline and can arrange support and shelter.",
            StepSource.DETERMINISTIC,
        ),
    ]
    workflow.alternatives = [
        WorkflowStep(
            "If you cannot speak, 112 also accepts SMS, and the ERSS app has a "
            "panic button.",
            StepSource.DETERMINISTIC,
        ),
        WorkflowStep(
            "If calling is not safe, messaging someone you trust to call for you "
            "works too.",
            StepSource.DETERMINISTIC,
        ),
    ]
    workflow.share = [
        WorkflowStep(
            "You can send a trusted person your location and what is happening. "
            "You choose what to send and when.",
            StepSource.DETERMINISTIC,
        ),
    ]
    workflow.limitations = [
        "HerWay cannot call anyone for you and cannot tell anyone where you are. "
        "Only you can do that, from your own phone.",
        "We cannot say how quickly anyone will respond.",
    ]
    return workflow


# ---------------------------------------------------------------------------
# Building a workflow
# ---------------------------------------------------------------------------

#: Above this, a response stops being a plan and becomes a wall of text.
MAX_DO_NOW = 3
MAX_NEXT = 5


def build_workflow(
    *,
    urgency: Optional[Urgency] = None,
    workflow_type: Optional[SafetyWorkflow] = None,
    suggested_steps: Optional[Sequence[WorkflowStep]] = None,
    limitations: Optional[Sequence[str]] = None,
    needs_clarification: Optional[str] = None,
) -> ActionWorkflow:
    """Assemble a proportionate workflow.

    Critical urgency short-circuits to :func:`emergency_fallback` and merges any
    research-backed steps after it — getting safe comes before everything, and
    that ordering must not depend on what a model returned.
    """
    if urgency is Urgency.CRITICAL or workflow_type is SafetyWorkflow.EMERGENCY:
        workflow = emergency_fallback()
        extra = strip_confrontation(
            [s for s in (suggested_steps or []) if s.source is StepSource.RESEARCH]
        )
        workflow.next_steps.extend(extra[:MAX_NEXT])
        if limitations:
            workflow.limitations.extend(limitations)
        return workflow

    workflow = ActionWorkflow(needs_clarification=needs_clarification)
    steps = strip_confrontation(list(suggested_steps or []))

    # Research-backed steps lead: they are the ones with a source behind them.
    ranked = sorted(steps, key=lambda s: 0 if s.source is StepSource.RESEARCH else 1)

    workflow.do_now = ranked[:MAX_DO_NOW]
    workflow.next_steps = ranked[MAX_DO_NOW : MAX_DO_NOW + MAX_NEXT]
    workflow.save = [s for s in ranked if s.source is StepSource.RESEARCH][:5]

    if limitations:
        workflow.limitations.extend(limitations)
    if any(s.source is StepSource.GENERATED for s in workflow.do_now + workflow.next_steps):
        workflow.limitations.append(
            "Some steps here are suggestions rather than information checked "
            "against an official source."
        )
    return workflow


def from_action_plan(action_plan, *, urgency: Optional[Urgency] = None) -> ActionWorkflow:
    """Bucket an existing ``ActionPlan`` from ``action_planner``.

    Reads defensively via ``getattr`` so a change to ``ActionItem`` cannot break
    this, and so it also accepts the safety-plan action shape.
    """
    steps: List[WorkflowStep] = []
    for item in getattr(action_plan, "actions", []) or []:
        urls = list(getattr(item, "source_urls", None) or [])
        evidence = getattr(item, "evidence_ids", None) or []
        steps.append(
            WorkflowStep(
                text=getattr(item, "title", "") or getattr(item, "description", ""),
                source=StepSource.RESEARCH if (urls or evidence) else StepSource.GENERATED,
                source_urls=urls,
            )
        )
    return build_workflow(urgency=urgency, suggested_steps=steps)
